### ISSUE TITLE
vile advertising

### ISSUE THREAD

**Issue by ayunami2000** [ReperakPro/LEAP#1]
![image](https://user-images.githubusercontent.com/24785136/98448543-bc6b6600-20fa-11eb-8434-cc8581c31e5c.png)

**Comment by ReperakPro** [comment]
Joke issues are not allowed here. Closed.

**Comment by ayunami2000** [comment]
but its not a joke its quite real

**Comment by ReperakPro** [comment]
GitHub is not the place to discuss this.

**Comment by ayunami2000** [comment]
your mom
