### ISSUE TITLE
I FOUND UR EASTER EGGGGGGG

### ISSUE THREAD

**Issue by TFTWPhoenix** [ReperakPro/LEAP#3]
Damn daniel thats a good easter egg =PPPP

**Comment by Roizor** [comment]
Damn.java

why are you everywhere

**Comment by Roizor** [comment]
tee F tee W phee nix why are you everywhere I am

**Comment by TFTWPhoenix** [comment]
> tee F tee W phee nix why are you everywhere I am

Because I want. Also I saw "+ Easter Egg" in a commit and HAD to find it. (And then tell @ReperakPro i found it)

**Comment by TFTWPhoenix** [comment]
@ReperakPro how have u not closed this yet. I'll close it for you. There was never an issue here Mr. @ReperakPro.
